============================= test session starts ==============================
platform linux -- Python 3.6.13, pytest-7.0.1, pluggy-1.0.0 -- /env/ds/anaconda/envs/pipeline/bin/python
cachedir: .pytest_cache
rootdir: /app, configfile: setup.cfg
plugins: asyncio-0.16.0
collecting ... collected 1 item

tests/test_json/test_integration/test_client.py::TestGrpcServerWithoutSSL::test_ok_flow 

============================ no tests ran in 1.29s =============================
Traceback (most recent call last):
  File "/env/ds/anaconda/envs/pipeline/lib/python3.6/site-packages/_pytest/main.py", line 268, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File "/env/ds/anaconda/envs/pipeline/lib/python3.6/site-packages/_pytest/main.py", line 322, in _main
    config.hook.pytest_runtestloop(session=session)
  File "/env/ds/anaconda/envs/pipeline/lib/python3.6/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/env/ds/anaconda/envs/pipeline/lib/python3.6/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/env/ds/anaconda/envs/pipeline/lib/python3.6/site-packages/pluggy/_callers.py", line 60, in _multicall
    return outcome.get_result()
  File "/env/ds/anaconda/envs/pipeline/lib/python3.6/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/env/ds/anaconda/envs/pipeline/lib/python3.6/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/env/ds/anaconda/envs/pipeline/lib/python3.6/site-packages/_pytest/main.py", line 347, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File "/env/ds/anaconda/envs/pipeline/lib/python3.6/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/env/ds/anaconda/envs/pipeline/lib/python3.6/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/env/ds/anaconda/envs/pipeline/lib/python3.6/site-packages/pluggy/_callers.py", line 60, in _multicall
    return outcome.get_result()
  File "/env/ds/anaconda/envs/pipeline/lib/python3.6/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/env/ds/anaconda/envs/pipeline/lib/python3.6/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/env/ds/anaconda/envs/pipeline/lib/python3.6/site-packages/_pytest/runner.py", line 113, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File "/env/ds/anaconda/envs/pipeline/lib/python3.6/site-packages/_pytest/runner.py", line 126, in runtestprotocol
    rep = call_and_report(item, "setup", log)
  File "/env/ds/anaconda/envs/pipeline/lib/python3.6/site-packages/_pytest/runner.py", line 221, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
  File "/env/ds/anaconda/envs/pipeline/lib/python3.6/site-packages/_pytest/runner.py", line 261, in call_runtest_hook
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
  File "/env/ds/anaconda/envs/pipeline/lib/python3.6/site-packages/_pytest/runner.py", line 340, in from_call
    result: Optional[TResult] = func()
  File "/env/ds/anaconda/envs/pipeline/lib/python3.6/site-packages/_pytest/runner.py", line 261, in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
  File "/env/ds/anaconda/envs/pipeline/lib/python3.6/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/env/ds/anaconda/envs/pipeline/lib/python3.6/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/env/ds/anaconda/envs/pipeline/lib/python3.6/site-packages/pluggy/_callers.py", line 60, in _multicall
    return outcome.get_result()
  File "/env/ds/anaconda/envs/pipeline/lib/python3.6/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/env/ds/anaconda/envs/pipeline/lib/python3.6/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/env/ds/anaconda/envs/pipeline/lib/python3.6/site-packages/_pytest/runner.py", line 156, in pytest_runtest_setup
    item.session._setupstate.setup(item)
  File "/env/ds/anaconda/envs/pipeline/lib/python3.6/site-packages/_pytest/runner.py", line 498, in setup
    col.setup()
  File "/env/ds/anaconda/envs/pipeline/lib/python3.6/site-packages/_pytest/unittest.py", line 204, in setup
    self._request._fillfixtures()
  File "/env/ds/anaconda/envs/pipeline/lib/python3.6/site-packages/_pytest/fixtures.py", line 578, in _fillfixtures
    item.funcargs[argname] = self.getfixturevalue(argname)
  File "/env/ds/anaconda/envs/pipeline/lib/python3.6/site-packages/_pytest/fixtures.py", line 591, in getfixturevalue
    fixturedef = self._get_active_fixturedef(argname)
  File "/env/ds/anaconda/envs/pipeline/lib/python3.6/site-packages/_pytest/fixtures.py", line 610, in _get_active_fixturedef
    self._compute_fixture_value(fixturedef)
  File "/env/ds/anaconda/envs/pipeline/lib/python3.6/site-packages/_pytest/fixtures.py", line 693, in _compute_fixture_value
    fixturedef.execute(request=subrequest)
  File "/env/ds/anaconda/envs/pipeline/lib/python3.6/site-packages/_pytest/fixtures.py", line 1068, in execute
    result = hook.pytest_fixture_setup(fixturedef=self, request=request)
  File "/env/ds/anaconda/envs/pipeline/lib/python3.6/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/env/ds/anaconda/envs/pipeline/lib/python3.6/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/env/ds/anaconda/envs/pipeline/lib/python3.6/site-packages/pluggy/_callers.py", line 60, in _multicall
    return outcome.get_result()
  File "/env/ds/anaconda/envs/pipeline/lib/python3.6/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/env/ds/anaconda/envs/pipeline/lib/python3.6/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/env/ds/anaconda/envs/pipeline/lib/python3.6/site-packages/_pytest/fixtures.py", line 1122, in pytest_fixture_setup
    result = call_fixture_func(fixturefunc, request, kwargs)
  File "/env/ds/anaconda/envs/pipeline/lib/python3.6/site-packages/_pytest/fixtures.py", line 917, in call_fixture_func
    fixture_result = next(generator)
  File "/env/ds/anaconda/envs/pipeline/lib/python3.6/site-packages/_pytest/unittest.py", line 157, in fixture
    setup()
  File "/app/tests/test_json/test_integration/test_client.py", line 190, in setUpClass
    time.sleep(BaseGrpcTestCase.TestGrpcServer.TIMEOUT)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/env/ds/anaconda/envs/pipeline/bin/pytest", line 8, in <module>
    sys.exit(console_main())
  File "/env/ds/anaconda/envs/pipeline/lib/python3.6/site-packages/_pytest/config/__init__.py", line 188, in console_main
    code = main()
  File "/env/ds/anaconda/envs/pipeline/lib/python3.6/site-packages/_pytest/config/__init__.py", line 166, in main
    config=config
  File "/env/ds/anaconda/envs/pipeline/lib/python3.6/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/env/ds/anaconda/envs/pipeline/lib/python3.6/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/env/ds/anaconda/envs/pipeline/lib/python3.6/site-packages/pluggy/_callers.py", line 60, in _multicall
    return outcome.get_result()
  File "/env/ds/anaconda/envs/pipeline/lib/python3.6/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/env/ds/anaconda/envs/pipeline/lib/python3.6/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/env/ds/anaconda/envs/pipeline/lib/python3.6/site-packages/_pytest/main.py", line 315, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/env/ds/anaconda/envs/pipeline/lib/python3.6/site-packages/_pytest/main.py", line 282, in wrap_session
    config.hook.pytest_keyboard_interrupt(excinfo=excinfo)
  File "/env/ds/anaconda/envs/pipeline/lib/python3.6/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/env/ds/anaconda/envs/pipeline/lib/python3.6/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/env/ds/anaconda/envs/pipeline/lib/python3.6/site-packages/pluggy/_callers.py", line 60, in _multicall
    return outcome.get_result()
  File "/env/ds/anaconda/envs/pipeline/lib/python3.6/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/env/ds/anaconda/envs/pipeline/lib/python3.6/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/env/ds/anaconda/envs/pipeline/lib/python3.6/site-packages/_pytest/terminal.py", line 826, in pytest_keyboard_interrupt
    self._keyboardinterrupt_memo = excinfo.getrepr(funcargs=True)
  File "/env/ds/anaconda/envs/pipeline/lib/python3.6/site-packages/_pytest/_code/code.py", line 666, in getrepr
    return fmt.repr_excinfo(self)
  File "/env/ds/anaconda/envs/pipeline/lib/python3.6/site-packages/_pytest/_code/code.py", line 926, in repr_excinfo
    reprtraceback = self.repr_traceback(excinfo_)
  File "/env/ds/anaconda/envs/pipeline/lib/python3.6/site-packages/_pytest/_code/code.py", line 867, in repr_traceback
    reprentry = self.repr_traceback_entry(entry, einfo)
  File "/env/ds/anaconda/envs/pipeline/lib/python3.6/site-packages/_pytest/_code/code.py", line 810, in repr_traceback_entry
    source = self._getentrysource(entry)
  File "/env/ds/anaconda/envs/pipeline/lib/python3.6/site-packages/_pytest/_code/code.py", line 718, in _getentrysource
    source = entry.getsource(self.astcache)
  File "/env/ds/anaconda/envs/pipeline/lib/python3.6/site-packages/_pytest/_code/code.py", line 261, in getsource
    self.lineno, source, astnode=astnode
  File "/env/ds/anaconda/envs/pipeline/lib/python3.6/site-packages/_pytest/_code/source.py", line 187, in getstatementrange_ast
    start, end = get_statement_startend2(lineno, astnode)
  File "/env/ds/anaconda/envs/pipeline/lib/python3.6/site-packages/_pytest/_code/source.py", line 150, in get_statement_startend2
    for x in ast.walk(node):
  File "/env/ds/anaconda/envs/pipeline/lib/python3.6/ast.py", line 225, in walk
    todo.extend(iter_child_nodes(node))
  File "/env/ds/anaconda/envs/pipeline/lib/python3.6/ast.py", line 183, in iter_child_nodes
    for name, field in iter_fields(node):
  File "/env/ds/anaconda/envs/pipeline/lib/python3.6/ast.py", line 175, in iter_fields
    pass
KeyboardInterrupt
